### ISSUE TITLE
Migration from non-docker 0.1.4 to latest docker image failed

### ISSUE THREAD

**Issue by PandaScience** [sharelatex/sharelatex#439]
Hi@all,

recently we decided to migrate our server including the ShareLaTeX setup to some better hardware. 
The sharelatex v0.1.4 had been installed manually (no docker image) on a debian 8 virtual machine. On the new machine, we wanted to use the recommended docker image. For the new installation everything works fine. I created a new user, tested an example project etc... 

But when I move the old mongo database via mongodump & mongorestore and copy the contents of /var/lib/sharelatex/ , then we have all files and users as before but suddenly compilation won't work anymore. Only an error 

> "Sorry, something went wrong and your project could not be compiled"

is displayed, even for newly created example projects. How can that happen when only the database is replaced? It's not like the compiler was not installed or some missing latexmk or zero-byte files reported in other issues. 

Is there maybe something in the database pointing to a specific compiler path or the like? 

Any help would be appreciated :).

**Comment by henryoswald** [comment]
Hi,

if you go into the database and do a:

db.projects.find({_id:ObjectId('MY_PROJECT_ID')})

what is returned?

**Comment by PandaScience** [comment]
Hi again, 

always impressed by the lightning-fast support here :+1: 

it returns:
> 2016-06-15T18:22:20.190+0000 Error: invalid object id: length

**Comment by henryoswald** [comment]
I think the command is a bit wrong, do you have the id in quotes or copied only part of it?

**Comment by PandaScience** [comment]
Hm, maybe I'm doing sth else wrong? The command should be exactly what you posted.

![mongodb_error](https://cloud.githubusercontent.com/assets/8038521/16094307/eff08ddc-333f-11e6-85fa-5f67ebdb5e8b.png)

**Comment by henryoswald** [comment]
you have to replace MY_PROJECT_ID with the id of the project you are trying to open. i.e 576000409888366100264018

**Comment by PandaScience** [comment]
Oh...that was embarrassing. I'm a real noob on databases. Here the output:

![mongo2](https://cloud.githubusercontent.com/assets/8038521/16094544/f7a81788-3340-11e6-858c-2b3023e47e34.png)

**Comment by henryoswald** [comment]
and if you do db.docs.find({project_id:ObjectId("PROJECT_ID_HERE")})

**Comment by PandaScience** [comment]
Ok, so when I use one of the imported project IDs the content of the source files is returned. In case I use the same ID as before (newly created project after migration), nothing is returned.

**Comment by henryoswald** [comment]
sorry just to check

- old projects = data is returned?
- new projects = nothing is returned?

do you have a backup of your database?

**Comment by PandaScience** [comment]
jep. I repeated the import steps several times on a virtual machine for testing. After the old projects didn't compile (because of possible lack of special packages like revtex-4 etc.) I created a new example project that did compile perfectly when starting an entirely new database, but did not when replacing the database + files in `/var/lib/sharelatex`. 

Database should rest (hopefully complete?) save on another server. 

The steps for importing the old data have been:

On the old server:
  * `mongodump --out /some/path`
  * `scp -r /var/lib/sharelatex  fileserver:/backup/path`

On the testing VM:
  * install debian 8.5 + docker
  * use the variant from beniodtldr [here](https://github.com/sharelatex/sharelatex-docker-image/issues/2), i.e.
    * `sudo docker run -d --name sharemongo -v /var/mongodb:/data/db mongo:2.6`
    * copy dumped mongo database to docker instance and import it using mongorestore
    * `sudo docker run -d --name shareredis -v /var/redis:/var/lib/redis redis:latest`
    * `sudo docker run -d -P -p 5000:80 -v /var/sharelatex:/var/lib/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --env SHARELATEX_ADMIN_EMAIL=rene.wirnata@physik.tu-freiberg.de --link sharemongo:mongo --link shareredis:redis --name sharelatex sharelatex/sharelatex`
  * replace the files in `/var/sharelatex/*` on the host with the backed up ones from the old server
  * restart sharelatex docker instance
  * try to compile and/or create new test project

**Comment by henryoswald** [comment]
i've just pushed up a new version sharelatex/sharelatex:v0.3.3 can you try that out and see how it goes? maybe try without the new db and see what happens as well.

**Comment by PandaScience** [comment]
Ok. Now there is some different behavior:

When importing the old DB, on the first start of the sharelatex instance it will hang up (see pic). On 2nd start, compiling will work for new projects and as far as I can test right now also for old (imported) ones. I still get some errors but they are related to missing packages for document classes and/or missing xetex compiler (full texlive install will take a while).

  * db.projects.find() will return reasonable stuff for both, new and old projects
  * db.docs.find() will return nothing for both, new and old projects

![mongo3](https://cloud.githubusercontent.com/assets/8038521/16097447/24595622-334e-11e6-9705-20bfbf6802df.png)

For a fresh start without importing anything, the container will crash on the first start with 

![mongo4](https://cloud.githubusercontent.com/assets/8038521/16097604/f03c6626-334e-11e6-8879-83fa58104fe8.png)

After creating the sqlite db by hand using `touch /var/sharelatex/data/db.sqlite` it will start, but again hang at "migration done" as above. On the 3rd try, it will finally start till ready for serving and it will also compile a first example project.

**Comment by PandaScience** [comment]
I can confirm now that all projects compile or at least run the compiler with v0.3.3 after doing a full texlive installation.

However, I still encountered many problems with the texlive-2016 used in the new version since our university latex package is not texlive-2016-ready yet. Is there a way to downgrade to 2015? As far as I've understood docker, this stuff is set in the dockerfile and for sharelatex it seems to point simply to the latest texlive version which is 2016 as of 05-Jun-16. Would it be possible to build an image v0.3.3-texlive2015 or the like? 

Sorry for bothering so much.

**Comment by henryoswald** [comment]
great stuff.

**Comment by PandaScience** [comment]
Thanks a lot again, you saved the day :+1:
